version: "3" #versione di docker compose

services: #servizi richiesti nel progetto
  app: #nome del servizio
    build:
      context: . #'.'->current directory
    ports: 
      - "8000:8000" #porta host, porta container
    volumes:
      - ./app:/app #mappa la folder del workspace nella folder nell'immagine, automatizzando gli update
    command: > #andare a capo, per comprensibilità
      sh -c "python3 manage.py 0.0.0.0:8000" #comando shell per lanciare django 
      #sull'address specificato, 0.0.0.0 per il container 